<%@ page pageEncoding="UTF-8" %>
<%@ page import="com.campusconnect.web.Document" %>
<%! private String navSafe(String value) { if (value == null) return ""; return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&#39;"); } %>
<%
String activeModule = (String) request.getAttribute("activeModule");
if (activeModule == null) activeModule = "";
Document navUser = (Document) session.getAttribute("user");
String navName = navUser == null || navUser.getString("name") == null ? "Student" : navUser.getString("name");
%>
<nav class="topbar"><button class="mobile-nav-toggle" type="button" onclick="document.querySelector('.sidebar').classList.toggle('open')" aria-label="Open navigation">&#9776;</button><a class="brand" href="${pageContext.request.contextPath}/dashboard"><span class="brand-mark">C</span><span>Campus Connect<small>Student collaboration hub</small></span></a><div class="top-actions"><a class="quick-create" href="${pageContext.request.contextPath}/marketplace">＋ Create</a><span class="nav-greeting">Hi, <%= navSafe(navName) %></span><a class="avatar mini" href="${pageContext.request.contextPath}/profile"><%= navSafe(navName.substring(0, 1).toUpperCase()) %></a><a class="logout-link" href="${pageContext.request.contextPath}/auth?action=logout">Log out</a></div></nav>
<aside class="sidebar"><p class="eyebrow">WORKSPACE</p><a class="<%= "dashboard".equals(activeModule) ? "active" : "" %>" href="${pageContext.request.contextPath}/dashboard"><span>⌂</span> Overview</a><a class="<%= "notes".equals(activeModule) ? "active" : "" %>" href="${pageContext.request.contextPath}/notes"><span>▤</span> Notes library</a><a class="<%= "questions".equals(activeModule) ? "active" : "" %>" href="${pageContext.request.contextPath}/questions"><span>?</span> Q&amp;A</a><a class="<%= "assignments".equals(activeModule) ? "active" : "" %>" href="${pageContext.request.contextPath}/assignments"><span>✦</span> Peer support</a><a class="<%= "marketplace".equals(activeModule) ? "active" : "" %>" href="${pageContext.request.contextPath}/marketplace"><span>▣</span> Marketplace</a><a class="<%= "projects".equals(activeModule) ? "active" : "" %>" href="${pageContext.request.contextPath}/projects"><span>◇</span> Projects</a><a href="${pageContext.request.contextPath}/activity"><span>?</span> Activity feed</a><a class="<%= "profiles".equals(activeModule) ? "active" : "" %>" href="${pageContext.request.contextPath}/profiles"><span>?</span> People &amp; messages</a><a href="${pageContext.request.contextPath}/note-requests"><span>+</span> Note requests</a><p class="eyebrow mt-4">ACCOUNT</p><a class="<%= "profile".equals(activeModule) ? "active" : "" %>" href="${pageContext.request.contextPath}/profile"><span>◉</span> Profile</a><a class="<%= "notifications".equals(activeModule) ? "active" : "" %>" href="${pageContext.request.contextPath}/notifications"><span>◌</span> Campus notices</a><div class="sidebar-footer"><strong>Campus tip</strong><p>Share one useful thing today.</p></div></aside>
