<%@ page contentType="text/html;charset=UTF-8" %>
<%@ page import="com.campusconnect.web.Document,java.util.List" %>
<%! private String esc(Object v){return v==null?"":String.valueOf(v).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
private String text(Object v){if(v instanceof java.util.List){StringBuilder out=new StringBuilder(); for(Object item:(java.util.List)v){if(out.length()>0) out.append(", "); out.append(String.valueOf(item));} return out.toString();} return v==null?"":String.valueOf(v);} %>
<% List<Document> people=(List<Document>)request.getAttribute("people"); List<Document> messages=(List<Document>)request.getAttribute("messages"); Document selected=(Document)request.getAttribute("selected"); Document me=(Document)session.getAttribute("user"); %>
<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>People & messages · Campus Connect</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/campus.css"></head>
<body><% request.setAttribute("activeModule","profiles"); %><%@ include file="_app-nav.jsp" %><div class="layout"><main class="content people-page">
<div class="page-head"><p class="eyebrow">CAMPUS NETWORK</p><h1>People & messages</h1><p class="text-secondary">Discover classmates, mentors, and peer teachers, then message them without leaving the directory.</p></div>
<form class="toolbar profile-search" method="get"><input class="form-control" name="q" value="<%=esc(request.getAttribute("query"))%>" placeholder="Search by name, course, skill, or interest"><input class="form-control" name="course" value="<%=esc(request.getAttribute("course"))%>" placeholder="Filter by course"><button class="btn btn-primary">Search people</button><a class="clear-filter" href="${pageContext.request.contextPath}/profiles">Clear filters</a></form>
<div class="people-messages-layout"><section class="people-panel"><div class="section-head"><div><p class="eyebrow">DIRECTORY</p><h2>Find your people</h2></div><span class="count-badge"><%=people.size()%> people</span></div><div class="profile-directory"><% for(Document p:people){ String name=p.getString("name"); String initial=name==null?"?":name.substring(0,1).toUpperCase(); String skills=text(p.get("skills")); String github=text(p.get("githubUrl")); %><article class="panel directory-card <%=selected!=null&&selected.getObjectId("_id").equals(p.getObjectId("_id"))?"active-person":""%>"><div class="directory-avatar"><%=esc(initial)%></div><div class="directory-card-body"><div class="person-heading"><h3><%=esc(name)%> <%if(p.getBoolean("verified",false)){%><span class="verified-badge">Verified</span><%}%></h3><span class="availability-dot <%=esc(p.getString("availability"))%>"><%=esc(p.getString("availability")==null?"Available":p.getString("availability"))%></span></div><p class="text-secondary"><%=esc(p.getString("course"))%> · Year <%=esc(p.getString("year"))%></p><p><%=esc(p.getString("bio"))%></p><div class="tag-list"><span><%=esc(skills)%></span></div><div class="directory-actions"><a class="btn btn-sm btn-primary" href="${pageContext.request.contextPath}/profiles?with=<%=p.getObjectId("_id")%>">Message</a><%if(!github.isBlank()){%><a class="btn btn-sm btn-outline-dark" href="<%=esc(github)%>" target="_blank" rel="noopener">GitHub ↗</a><%}%></div></div></article><% } %><%if(people.isEmpty()){%><div class="empty">No people match those filters.</div><%}%></div></section>
<section class="panel thread-panel combined-thread"><%if("true".equals(request.getParameter("sent"))){%><div class="alert alert-success">Message sent.</div><%}else if("message".equals(request.getParameter("error"))){%><div class="alert alert-danger">Enter a message and select a valid recipient.</div><%}%><%if(selected==null){%><div class="thread-empty"><div class="thread-empty-icon">✦</div><h2>Start a conversation</h2><p>Select a person from the directory to view your private conversation here.</p></div><%}else{String selectedName=selected.getString("name");%><div class="thread-header"><div class="directory-avatar"><%=esc(selectedName==null?"?":selectedName.substring(0,1).toUpperCase())%></div><div class="thread-person"><h2><%=esc(selectedName)%></h2><small><%=esc(selected.getString("course"))%> · <%=esc(selected.getString("bio"))%></small></div><a class="thread-close" href="${pageContext.request.contextPath}/profiles">×</a></div><div class="message-list"><%if(messages!=null&&!messages.isEmpty())for(Document m:messages){boolean mine=me.getObjectId("_id").equals(m.getObjectId("senderId"));%><div class="message-bubble <%=mine?"mine":""%>"><p><%=esc(m.getString("body"))%></p><small><%=esc(m.getString("createdAt"))%></small></div><%}else{%><div class="empty">No messages yet. Say hello and start the conversation.</div><%}%></div><form class="message-compose" method="post" action="${pageContext.request.contextPath}/messages"><input type="hidden" name="recipientId" value="<%=selected.getObjectId("_id")%>"><textarea name="body" class="form-control" maxlength="2000" required placeholder="Write a thoughtful message…"></textarea><button class="btn btn-primary">Send message</button></form><%}%></section></div>
</main></div></body></html>
